"""empty message

Revision ID: bb0b1f5c508c
Revises: 
Create Date: 2020-04-02 11:42:44.198223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb0b1f5c508c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('book_title', sa.String(), nullable=False))
    op.drop_column('book', 'title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('book', 'book_title')
    # ### end Alembic commands ###
