"""empty message

Revision ID: f12ed40de821
Revises: 621295a322ca
Create Date: 2020-03-31 16:33:18.586169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f12ed40de821'
down_revision = '621295a322ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review', sa.Column('book_id', sa.Integer(), nullable=False))
    op.add_column('review', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'review', 'book', ['book_id'], ['id'])
    op.create_foreign_key(None, 'review', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'review', type_='foreignkey')
    op.drop_constraint(None, 'review', type_='foreignkey')
    op.drop_column('review', 'user_id')
    op.drop_column('review', 'book_id')
    # ### end Alembic commands ###
