# Generated by Django 2.2.5 on 2020-10-02 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20201001_2311'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='listing',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='listing',
            new_name='item',
        ),
    ]
