# Generated by Django 2.2.5 on 2020-10-08 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_listing_watchers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='watchers',
        ),
    ]
