# Generated by Django 2.2.5 on 2020-10-08 19:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_remove_listing_watchers'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='watcher',
            field=models.ManyToManyField(blank=True, related_name='watched_items', to=settings.AUTH_USER_MODEL),
        ),
    ]
